version: "1"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1ch235db09
      MYSQL_DATABASE: collectify
    volumes:
      - collectify-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  collectify-mysql-data: